# Practica con numpy

## Crear un arreglo multidimensional

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
a1 = np.array(([1,2,3,4,5],[6,7,8,9,10]))
a1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
a2 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [9]:
a2.ndim

3

In [10]:
a2.shape

(2, 2, 2)

In [18]:
a3=np.zeros((2,3,2))
a3

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [20]:
a4 = np.ones((3,5))
a4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
a5 = np.arange(10)
a5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
a6 = np.arange(15).reshape(3,5)
a6

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [55]:
a7 = np.eye(5)
a7

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Funciones básicas de arreglos

In [29]:
a6.dtype

dtype('int64')

In [30]:
a6.shape

(3, 5)

In [31]:
a6.size

15

In [32]:
a6.ndim

2

## Operaciones Básicas en arreglos

In [33]:
a = np.array([10,20,30,40,50])
b = np.arange(5)*100

array([  0, 100, 200, 300, 400])

In [34]:
print(a)
print(b)

[10 20 30 40 50]
[  0 100 200 300 400]


In [35]:
a+b

array([ 10, 120, 230, 340, 450])

In [36]:
a-b

array([  10,  -80, -170, -260, -350])

In [37]:
a*b       #producto elemento a elemento

array([    0,  2000,  6000, 12000, 20000])

In [38]:
a@b       # producto punto

40000

In [39]:
a.dot(b)

40000

In [40]:
c = np.random.random((2,3))
c

array([[0.53997871, 0.07105204, 0.72532922],
       [0.16600889, 0.36457669, 0.92294872]])

In [41]:
c.min()

0.07105204076818927

In [42]:
c.max()

0.922948719429739

In [43]:
c.sum()

2.7898942656341945

In [44]:
d = np.arange(12).reshape(3,4)
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
d.sum(axis=0)

array([12, 15, 18, 21])

In [47]:
d.sum(axis=1)

array([ 6, 22, 38])

In [48]:
d.cumsum(axis =1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

## Manupulación de dimensiones

In [49]:
d.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [54]:
d = d.reshape(4,3)
d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [53]:
d.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

## Numpy Indexación y Selección

In [59]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr[6]

7

In [61]:
arr[1:5]

array([2, 3, 4, 5])

In [62]:
arr [0:5]

array([1, 2, 3, 4, 5])

In [63]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
arr[6:]

array([ 7,  8,  9, 10])

In [65]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [66]:
arr_2d[2][0] #  arr_2d[2,0]

35

In [68]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [69]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

# Ejercicios
1. Crear un arreglo de 10 zeros
2. Crear un arreglo de enteros de 10 a 50 
3. Reajusta el arreglo anterior para que tenga 5 filas
4. Crea una matriz de 5x5 de números aleatorios
5. Suma todos los valores de la matriz
6. Crea una matriz de 10*10 de números positivos y regresa la columna [3,5,7]
7. De la matriz anterior regresa las filas [0,6,9]